### PR TITLE
Resolve method later, prevents errors on oneway functions

### PR DESCRIPTION
**Pull request by virtuald**
When the server runs a oneway function and an error occurs, the error still gets sent back to the client. The java bindings discard the error, so the python bindings should also discard it.

### CODE REVIEW

**Comment by bergundy** [comment]
None of the python generators (tornado/blocking/twisted) generate recv_\* methods for oneway calls.
I also tried to generate java code and it also doesn't generate a recv_ method for oneway calls.

**Comment by virtuald** [comment]
That is correct, which is why I didn't add a recv_ method. However, the server still sends data back on an error, which results in an unhandled exception on the python client code. Try it. 

Additionally, this is marginally more efficient anyways, as the method is not actually used after the future is examined.

**Comment by bergundy** [comment]
@virtuald, this is not strictly a tornado issue, I think you should take this up with the official issue tracker.

**Comment by virtuald** [comment]
I realize that it's not a tornado issue -- but the fact that the tornado bindings crash when it occurs _is_ a tornado issue. 

The java client disregards the incoming recv_ call from the server. The tornado bindings should do the same thing.

Without this patch, the incoming response from the server hits the getattr() and it crashes because the function does not exist. With this patch, it gets discarded correctly, as there isn't a future registered by oneway functions.

**Comment by bergundy** [comment]
Agreed

**Comment by virtuald** [comment]
Thanks!

**Comment by bergundy** [comment]
Please submit this upstream as well

**Comment by virtuald** [comment]
Ah, for some reason I thought that bit of code was introduced by your changed, will do.

**Pull request merged**
