### PR TITLE
Fix incorrect indentation when oneway function is used

### PR DESCRIPTION
**Pull request by virtuald**
The shortcut doesn't work, the next function ends up getting generated inside the previous function, which is bad.

### CODE REVIEW

**Comment by bergundy** [comment]
This is incorrect behavior, see: https://github.com/bergundy/thrift/pull/6

**Comment by virtuald** [comment]
This commit did not add the oneway function back in. Have you tried generating an interface with a oneway function and a non-oneway function in it? The indentation is incorrect.

**Comment by bergundy** [comment]
You're correct, I merged it

**Comment by virtuald** [comment]
Thanks!

**Comment by bergundy** [comment]
Do you mind taking this pull request upstream?

**Comment by virtuald** [comment]
Sure thing.

**Pull request merged**
