### PR TITLE
Use coroutines for interface functions

### PR DESCRIPTION
**Pull request by virtuald**
This seems to fit tornado better, and solves https://github.com/bergundy/thrift/issues/1 and https://github.com/bergundy/thrift/issues/2.

### CODE REVIEW

**Comment by bergundy** [comment]
This is not a good idea, from the docs:

> If no callback is given, this method returns a Future that resolves (with a result of None) when the write has been completed. If write is called again before that Future has resolved, the previous future will be orphaned and will never resolve.

http://tornado.readthedocs.org/en/latest/iostream.html#tornado.iostream.BaseIOStream.write

**Comment by virtuald** [comment]
Interesting, point taken. I'll think about a workaround.

I still think that you do need the behavior of waiting until the write finishes, otherwise how else will clients be informed of an error? Additionally, it's consistent with how the other thrift bindings work.

**Comment by bergundy** [comment]
If you provide a better solution for this, I'd gladly accept it.

**Comment by virtuald** [comment]
Ok, so I think the only good solution is to put a toro lock inside the flush so only one write occurs at a time on the underlying socket. Other solutions are probably too complex -- and as it's a coroutine, if you really wanted to not block on it, you could just take the returned future and wait on that somewhere else. 

Since writers are waiting for a response to come back anyways, I don't believe performance will be any worse than what you would expect from a synchronous client. If performance turns out to be bad, then we could revisit this later. 

Also, it looks like your PR has been accepted upstream, so I'll take future issues there -- but I would love feedback on this change.

**Comment by bergundy** [comment]
That would work but I'd advise against it.
What you're suggesting is to add an implicit rate limiter to the client and it will definitely hurt performance, the blocking client has much less overhead (no coroutines, stack contexts, io loop).

I'm not sure how much we'll gain in waiting for the socket write to complete, it doesn't assure you that the request has reached the other side just that the data has been flushed to an OS buffer.

As for exceptions being swallowed, most of the time tornado will try to write to the OS buffer immediately so most write exceptions we'll be raised synchronously.
Since we're always reading, we'll get notification asynchronous write errors in the form of IOStream closed errors and any pending read futures will be triggered with an exception.
Except for oneway methods there's nothing to be gained by adding the lock.

To conclude, I think the current solution is better considering IOStream.write()'s limitations.

I'm also posting this discussion on the tornado mailing list to get more input.

**Comment by virtuald** [comment]
I think the thing that is most important to me (even above performance, for the moment) is not knowing what happens to unhandled exceptions. Under the current code, if an exception occurs during flush(), then the calling code will never be able to recover from it, as it will go unhandled. I've spent too many hours debugging code that was hiding errors from me to want to deal with that more than I need to.

I agree that getting more input on this would be helpful, I'm sure there has to be a better way to solve this.

**Pull request closed without merging**
